[package]
name = "opencv_ext"
version = "0.1.0"
edition = "2018"

[lib]
name = "opencv_ext"
proc-macro = true

[dependencies]
opencv = "0.55.0"
quote = "1.0"
anyhow = "1.0.44"
syn = { version = "1.0.80", features = ["fold"] }