[package]
name = "opencv_macro"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
anyhow = "1.0.44"
syn = { version = "1.0.80", features = ["derive", "fold", "extra-traits", "full"] }